name: Update Yarn Lockfile

on:
  push:
    paths:
      - "package.json"
  pull_request:
    paths:
      - "package.json"

jobs:
  update-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"

      - name: Install Dependencies
        run: yarn --frozen-lockfile=false

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add yarn.lock
          git commit -m "chore: update yarn.lock"
          git push
        continue-on-error: true  # Prevent failure if there's nothing to commit
